name: CI

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:    
    runs-on: windows-latest
    name: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build --configuration Release

  codeql-analysis:    
    name: CodeQL analysis
    runs-on: windows-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
        
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
